# 開発用Dockerfile（Dockerfile.dev）
FROM golang:1.24-alpine
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go install github.com/air-verse/air@latest
EXPOSE 8080
EXPOSE 8082
ENV GIN_MODE=debug
CMD ["air", "-c", ".air.toml"]
